using System;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using Microsoft.Phone.Notification;

namespace WindowsPhoneNotificationService
{
    /// <summary>
    /// Calls  web service to register or unregister for push notifications.
    /// </summary>
    public interface ServerService
    {
        /// <summary>
        /// Calls Register/Subscribe service of Web Service.
        /// </summary>
        /// <param name="deviceID">Unique Device ID</param>
        /// <param name="uri">Uri generated by Microsoft Push Notification Server</param>
        void Register(String deviceID,String uri);
        /// <summary>
        /// Calls Unregister/Unsubscribe service of Web Service.
        /// </summary>
        /// <param name="deviceID">Unique Device ID</param>
        void Unregister(String deviceID);

        /// <summary>
        /// Handles push notifications received while application is running.
        /// </summary>
        /// <param name="sender">Sender</param>
        /// <param name="e">Notification Event Args</param>
        void NotificationReceived(object sender, NotificationEventArgs e);
    }


}
